### ISSUE TITLE
When removing animated element from DOM without stopping, plugin produces an error

### ISSUE THREAD

**Issue by NenadP** [blaiprat/jquery.animateSprite#5]
If I remove the element from DOM where animatesprite was active, got error

Uncaught TypeError: Cannot read property 'start' of undefined

This currently solves issue for me, checking if it exists:

``` javascript
    var frame = function (frameNumber) {
        // frame: number of the frame to be displayed
        return this.each(function () {
            if (typeof $(this).data('animateSprite') != "undefined" ) {
                var $this = $(this),
                    data  = $this.data('animateSprite'),
                    row = Math.floor(frameNumber / data.settings.columns),
                    column = frameNumber % data.settings.columns;

                $this.css('background-position', (-data.settings.width * column) + 'px ' + (-data.settings.height * row) + 'px');
            }
        });
    };
```

Maybe there is better approach to this ?
(I can't predict all contexts and do proper stopAnimation)

**Comment by blaiprat** [comment]
Thanks for the report @NenadP , and sorry it took me so much to update the plugin. I've just pushed a new update using your approach plus another small tweak (changed the plugin to depend on setTimeout instead of setInterval, much safer!). 

I've tested it myself and it looks like it's working.
